config/routes.rb
Rails.application.routes.draw do

  get 'buscador/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'welcome#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'migration' => 'migration#index'
  post 'migration' => 'migration#upload'
  get 'buscador' => 'buscador#index'
  post 'buscador' => 'buscador#find'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user,   only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)

    if @user

      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Se envió un email para resetear la contraseña"
      redirect_to root_url
    else

      flash[:danger] = "Correo electrónico no encontrado"
      render 'new'
    end
  end

  def edit
  end

  def update

    if params[:user][:password].empty?

      @user.errors.add(:password, "no puede estar vacio")
      render 'edit'
    elsif @user.update_attributes(user_params)

      log_in @user
      flash[:success] = "La contraseña ha sido restablecida."
      redirect_to @user
    else

      render 'edit'
    end
  end

  private

    def user_params

      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user

      @user = User.find_by(email: params[:email])
    end

    def valid_user

      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))

        redirect_to root_url
      end
    end

    def check_expiration

      if @user.password_reset_expired?

        flash[:danger] = "El restablecimiento de la contraseña ha expirado."
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Recuperar Contraseña') %>
<h1>Restablecer Contraseña</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmar contraseña" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Actualizar Contraseña", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Olvidé Contraseña") %>
<h1>Recuperar Contraseña</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(:password_reset, url: password_resets_path) do |f| %>

			<%= f.label :email, "Correo electrónico" %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>