config/routes.rb
Rails.application.routes.draw do

  get 'buscador/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'welcome#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'migration' => 'migration#index'
  post 'migration' => 'migration#upload'
  get 'buscador' => 'buscador#index'
  post 'buscador' => 'buscador#find'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Secreataria de Educacion del Magdalena - 2016
  </small>
  <nav>
    <ul>
      <li><a href="http://magdalena.gov.co/index.shtml">Gobernación del Magdalena</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Secretaria de Educacion", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio",   root_url %></li>
        <% if logged_in? %>
        	<% if current_user.admin? && !current_user?(session[:user_id]) %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li><%= link_to "Registrar Usuario", signup_path %></li>
            <li><%= link_to "Migracion", migration_path %></li>
            <li><%= link_to "Buscador", buscador_path %></li>
        	<% end %>
        	<li class="dropdown user-dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @current_user.apellido+", "+@current_user.nombre %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Modificar Perfil", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Cerrar Sessión", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        	<li><%= link_to "Iniciar Sesión", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>